# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.FoCUS <- function(dataGen, thres, mu0, grid, K) {
    .Call(`_FOCuS_FOCuS`, dataGen, thres, mu0, grid, K)
}

.FoCUS_offline <- function(Y, thres, mu0, training_data, grid, K) {
    .Call(`_FOCuS_FOCuS_offline`, Y, thres, mu0, training_data, grid, K)
}

FOCuS_Melk <- function(Y, thres, mu0, grid, K) {
    .Call(`_FOCuS_FOCuS_melk`, Y, thres, mu0, grid, K)
}

.FoCUS_mult_offline <- function(Y, thres, mu0, training_data, grid, K) {
    .Call(`_FOCuS_FOCuS_mult_offline`, Y, thres, mu0, training_data, grid, K)
}

MOSUM_offline_kirch <- function(Y, thres, W) {
    .Call(`_FOCuS_MOSUM_offline_kirch`, Y, thres, W)
}

PageCUSUM_offline <- function(Y, thres, mu0, grid) {
    .Call(`_FOCuS_PageCUSUM_offline`, Y, thres, mu0, grid)
}

CUSUM_offline <- function(Y, thres, mu0) {
    .Call(`_FOCuS_CUSUM_offline`, Y, thres, mu0)
}

#' Function to update list of intervals (up or down) 
#'
#' @param n number of datapoints
#' @param sumAllX sum of all x_i up to n (For down change should give -sumAllX)   
#' @param tau vector of candidate changes
#' @param bound vector of interval bound m = (\mu1+\mu2)/2
#' @param sum vector of sum of x_i up to tau	 
#' @return void
NULL

#' Function to get the best cost given a set of candidate and there sum
#' 
#' @param n number of datapoints
#' @param sumAllX sum of all x_i up to n (For down change should give -sumAllX)   
#' @param tau vector of candidate changes
#' @param sum vector of sum of x_i up to tau	  
#' @return double
NULL

#' Function to run a Melkman-like algorithm for unknown first and second segment mean
#'
#' @param x datapoints
#' @param onlyPrune if TRUE only update intervals and does not compute the best cost at each step
#' @param exportInR if TRUE results (tau, bound and sum) are exported in R
#' @return Product of v1 and v2
.simpleMelkman <- function(x, onlyPrune, exportInR) {
    .Call(`_FOCuS_simpleMelkman`, x, onlyPrune, exportInR)
}

YuCUSUM_offline <- function(Y, thres) {
    .Call(`_FOCuS_YuCUSUM_offline`, Y, thres)
}

