# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.FoCUS <- function(dataGen, thres, mu0, grid, K) {
    .Call(`_FOCuS_FOCuS`, dataGen, thres, mu0, grid, K)
}

.FoCUS_offline <- function(Y, thres, mu0, grid, K) {
    .Call(`_FOCuS_FOCuS_offline`, Y, thres, mu0, grid, K)
}

FOCuS_melk <- function(Y, thres, mu0, grid, K) {
    .Call(`_FOCuS_FOCuS_melk`, Y, thres, mu0, grid, K)
}

PageCUSUM_offline <- function(Y, thres, mu0, grid) {
    .Call(`_FOCuS_PageCUSUM_offline`, Y, thres, mu0, grid)
}

CUSUM_offline <- function(Y, thres, mu0) {
    .Call(`_FOCuS_CUSUM_offline`, Y, thres, mu0)
}

start_profiler <- function(str) {
    .Call(`_FOCuS_start_profiler`, str)
}

stop_profiler <- function() {
    .Call(`_FOCuS_stop_profiler`)
}

test <- function() {
    invisible(.Call(`_FOCuS_test`))
}

