# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FOCuS_offline <- function(Y, thres) {
    .Call(`_FOCuS_FOCuS_offline`, Y, thres)
}

FOCuS_offline_V1 <- function(Y, thres) {
    .Call(`_FOCuS_FOCuS_offline_V1`, Y, thres)
}

start_profiler <- function(str) {
    .Call(`_FOCuS_start_profiler`, str)
}

stop_profiler <- function() {
    .Call(`_FOCuS_stop_profiler`)
}

test <- function() {
    invisible(.Call(`_FOCuS_test`))
}

